/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package paneles;

/**
 *
 * @author linke
 */
public class pnlConsulta extends javax.swing.JPanel {

    /**
     * Creates new form pnlConsulta
     */
    public pnlConsulta() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel13 = new javax.swing.JLabel();
        rSMTextFull11 = new rojeru_san.RSMTextFull();
        rSMTextFull13 = new rojeru_san.RSMTextFull();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel3 = new javax.swing.JPanel();
        rSMTextFull1 = new rojeru_san.RSMTextFull();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        rSTableMetro1 = new rojeru_san.complementos.RSTableMetro();
        jPanel1 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        rSMTextFull8 = new rojeru_san.RSMTextFull();
        rSMTextFull12 = new rojeru_san.RSMTextFull();
        rSMTextFull14 = new rojeru_san.RSMTextFull();
        rSComboMetro2 = new rojerusan.RSComboMetro();
        rSMTextFull15 = new rojeru_san.RSMTextFull();
        rSButton2 = new rojeru_san.RSButton();
        rSComboMetro6 = new rojerusan.RSComboMetro();
        rSComboMetro7 = new rojerusan.RSComboMetro();
        rSComboMetro8 = new rojerusan.RSComboMetro();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        PUESTO = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        rSMTextFull10 = new rojeru_san.RSMTextFull();
        rSMTextFull16 = new rojeru_san.RSMTextFull();
        rSMTextFull17 = new rojeru_san.RSMTextFull();
        rSComboMetro3 = new rojerusan.RSComboMetro();
        rSMTextFull18 = new rojeru_san.RSMTextFull();
        rSButton3 = new rojeru_san.RSButton();
        rSComboMetro9 = new rojerusan.RSComboMetro();
        rSComboMetro10 = new rojerusan.RSComboMetro();
        rSComboMetro11 = new rojerusan.RSComboMetro();
        rSButton4 = new rojeru_san.RSButton();

        jLabel13.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel13.setText("Paciente:");

        rSMTextFull11.setForeground(new java.awt.Color(51, 109, 136));
        rSMTextFull11.setText("rSMTextFull8");
        rSMTextFull11.setBordeColorFocus(new java.awt.Color(51, 109, 136));

        rSMTextFull13.setForeground(new java.awt.Color(51, 109, 136));
        rSMTextFull13.setText("rSMTextFull8");
        rSMTextFull13.setBordeColorFocus(new java.awt.Color(51, 109, 136));

        jPanel2.setBackground(new java.awt.Color(29, 27, 56));

        jLabel1.setFont(new java.awt.Font("Arial Black", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(231, 156, 194));
        jLabel1.setText("NUEVA CONSULTA");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(331, 331, 331)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jLabel1)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        jTabbedPane1.setBackground(new java.awt.Color(246, 190, 214));
        jTabbedPane1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N

        jPanel3.setBackground(new java.awt.Color(246, 190, 214));

        rSMTextFull1.setBackground(new java.awt.Color(246, 190, 214));
        rSMTextFull1.setForeground(new java.awt.Color(51, 109, 136));
        rSMTextFull1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        rSMTextFull1.setBordeColorFocus(new java.awt.Color(51, 109, 136));
        rSMTextFull1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/search.png"))); // NOI18N

        rSTableMetro1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Paciente", "Consulta", "Fecha", "Hora", "Estado"
            }
        ));
        rSTableMetro1.setAlignmentX(1.5F);
        rSTableMetro1.setAlignmentY(1.5F);
        rSTableMetro1.setAltoHead(75);
        rSTableMetro1.setColorBackgoundHead(new java.awt.Color(51, 109, 136));
        rSTableMetro1.setColorFilasBackgound2(new java.awt.Color(255, 255, 255));
        rSTableMetro1.setFuenteFilas(new java.awt.Font("Arial", 1, 12)); // NOI18N
        rSTableMetro1.setFuenteFilasSelect(new java.awt.Font("Arial", 1, 48)); // NOI18N
        rSTableMetro1.setFuenteHead(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        rSTableMetro1.setGridColor(new java.awt.Color(255, 255, 255));
        rSTableMetro1.setGrosorBordeHead(0);
        rSTableMetro1.setRowHeight(35);
        rSTableMetro1.setSelectionBackground(new java.awt.Color(231, 156, 194));
        jScrollPane1.setViewportView(rSTableMetro1);

        jPanel1.setBackground(new java.awt.Color(246, 190, 214));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel6.setText("Paciente:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(46, 94, -1, -1));

        jLabel7.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel7.setText("Datos de la consulta");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(72, 34, -1, -1));

        jLabel8.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel8.setText("Doctor:");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 151, -1, -1));

        jLabel9.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel9.setText("Fecha:");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 250, -1, -1));

        jLabel10.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel10.setText("Consulta:");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 200, -1, -1));

        jLabel11.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel11.setText("Hora:");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 250, -1, -1));

        jLabel12.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel12.setText("Total:");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 310, -1, -1));

        jLabel14.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel14.setText("Estado:");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 200, -1, -1));

        jLabel15.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel15.setText("Diagnostico:");
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 370, -1, -1));

        rSMTextFull8.setForeground(new java.awt.Color(51, 109, 136));
        rSMTextFull8.setBordeColorFocus(new java.awt.Color(51, 109, 136));
        jPanel1.add(rSMTextFull8, new org.netbeans.lib.awtextra.AbsoluteConstraints(123, 83, 409, -1));

        rSMTextFull12.setForeground(new java.awt.Color(51, 109, 136));
        rSMTextFull12.setBordeColorFocus(new java.awt.Color(51, 109, 136));
        jPanel1.add(rSMTextFull12, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 240, 132, -1));

        rSMTextFull14.setForeground(new java.awt.Color(51, 109, 136));
        rSMTextFull14.setBordeColorFocus(new java.awt.Color(51, 109, 136));
        jPanel1.add(rSMTextFull14, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 300, 401, -1));
        jPanel1.add(rSComboMetro2, new org.netbeans.lib.awtextra.AbsoluteConstraints(564, 221, 0, -1));

        rSMTextFull15.setForeground(new java.awt.Color(51, 109, 136));
        rSMTextFull15.setBordeColorFocus(new java.awt.Color(51, 109, 136));
        jPanel1.add(rSMTextFull15, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 240, 132, -1));

        rSButton2.setBackground(new java.awt.Color(51, 109, 136));
        rSButton2.setText("GUARDAR");
        jPanel1.add(rSButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 500, -1, -1));

        rSComboMetro6.setBackground(new java.awt.Color(51, 109, 136));
        rSComboMetro6.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Seleccione una opcion", "Activo", "..." }));
        rSComboMetro6.setColorArrow(new java.awt.Color(51, 109, 136));
        rSComboMetro6.setColorBorde(new java.awt.Color(51, 109, 136));
        rSComboMetro6.setColorFondo(new java.awt.Color(51, 109, 136));
        rSComboMetro6.setColorSeleccion(new java.awt.Color(51, 109, 136));
        rSComboMetro6.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jPanel1.add(rSComboMetro6, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 190, 138, -1));

        rSComboMetro7.setBackground(new java.awt.Color(51, 109, 136));
        rSComboMetro7.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Seleccione una opcion", "Dra. Soraya Cornejo" }));
        rSComboMetro7.setColorArrow(new java.awt.Color(51, 109, 136));
        rSComboMetro7.setColorBorde(new java.awt.Color(51, 109, 136));
        rSComboMetro7.setColorFondo(new java.awt.Color(51, 109, 136));
        rSComboMetro7.setColorSeleccion(new java.awt.Color(51, 109, 136));
        rSComboMetro7.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jPanel1.add(rSComboMetro7, new org.netbeans.lib.awtextra.AbsoluteConstraints(123, 143, 410, -1));

        rSComboMetro8.setBackground(new java.awt.Color(51, 109, 136));
        rSComboMetro8.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Seleccione una opcion", "Consulta general" }));
        rSComboMetro8.setColorArrow(new java.awt.Color(51, 109, 136));
        rSComboMetro8.setColorBorde(new java.awt.Color(51, 109, 136));
        rSComboMetro8.setColorFondo(new java.awt.Color(51, 109, 136));
        rSComboMetro8.setColorSeleccion(new java.awt.Color(51, 109, 136));
        rSComboMetro8.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jPanel1.add(rSComboMetro8, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 190, 138, -1));

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane4.setViewportView(jTextArea1);

        jPanel1.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 390, 410, -1));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(72, 72, 72)
                        .addComponent(rSMTextFull1, javax.swing.GroupLayout.PREFERRED_SIZE, 501, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 752, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(43, 43, 43)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(51, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rSMTextFull1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 556, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 556, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(99, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("CONSULTA", jPanel3);

        PUESTO.setBackground(new java.awt.Color(246, 190, 214));

        jPanel8.setBackground(new java.awt.Color(246, 190, 214));
        jPanel8.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jLabel16.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel16.setText("Paciente:");

        jLabel17.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel17.setText("Datos de la consulta");

        jLabel18.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel18.setText("Doctor:");

        jLabel19.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel19.setText("Fecha:");

        jLabel20.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel20.setText("Consulta:");

        jLabel21.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel21.setText("Hora:");

        jLabel22.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel22.setText("Total:");

        jLabel23.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel23.setText("Estado:");

        rSMTextFull10.setForeground(new java.awt.Color(51, 109, 136));
        rSMTextFull10.setBordeColorFocus(new java.awt.Color(51, 109, 136));

        rSMTextFull16.setForeground(new java.awt.Color(51, 109, 136));
        rSMTextFull16.setBordeColorFocus(new java.awt.Color(51, 109, 136));

        rSMTextFull17.setForeground(new java.awt.Color(51, 109, 136));
        rSMTextFull17.setBordeColorFocus(new java.awt.Color(51, 109, 136));

        rSMTextFull18.setForeground(new java.awt.Color(51, 109, 136));
        rSMTextFull18.setBordeColorFocus(new java.awt.Color(51, 109, 136));

        rSButton3.setBackground(new java.awt.Color(51, 109, 136));
        rSButton3.setText("GUARDAR");

        rSComboMetro9.setBackground(new java.awt.Color(51, 109, 136));
        rSComboMetro9.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Seleccione una opcion", "Doctor", "Secretaria" }));
        rSComboMetro9.setColorArrow(new java.awt.Color(51, 109, 136));
        rSComboMetro9.setColorBorde(new java.awt.Color(51, 109, 136));
        rSComboMetro9.setColorFondo(new java.awt.Color(51, 109, 136));
        rSComboMetro9.setColorSeleccion(new java.awt.Color(51, 109, 136));
        rSComboMetro9.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        rSComboMetro10.setBackground(new java.awt.Color(51, 109, 136));
        rSComboMetro10.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Seleccione una opcion", "Doctor", "Secretaria" }));
        rSComboMetro10.setColorArrow(new java.awt.Color(51, 109, 136));
        rSComboMetro10.setColorBorde(new java.awt.Color(51, 109, 136));
        rSComboMetro10.setColorFondo(new java.awt.Color(51, 109, 136));
        rSComboMetro10.setColorSeleccion(new java.awt.Color(51, 109, 136));
        rSComboMetro10.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        rSComboMetro11.setBackground(new java.awt.Color(51, 109, 136));
        rSComboMetro11.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Seleccione una opcion", "Doctor", "Secretaria" }));
        rSComboMetro11.setColorArrow(new java.awt.Color(51, 109, 136));
        rSComboMetro11.setColorBorde(new java.awt.Color(51, 109, 136));
        rSComboMetro11.setColorFondo(new java.awt.Color(51, 109, 136));
        rSComboMetro11.setColorSeleccion(new java.awt.Color(51, 109, 136));
        rSComboMetro11.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        rSButton4.setBackground(new java.awt.Color(255, 51, 51));
        rSButton4.setText("CANCELAR");

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel17)
                    .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel8Layout.createSequentialGroup()
                            .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel16)
                                .addComponent(jLabel18))
                            .addGap(18, 18, 18)
                            .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(rSMTextFull10, javax.swing.GroupLayout.DEFAULT_SIZE, 790, Short.MAX_VALUE)
                                .addComponent(rSComboMetro10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGroup(jPanel8Layout.createSequentialGroup()
                            .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(jPanel8Layout.createSequentialGroup()
                                    .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(rSMTextFull18, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(jPanel8Layout.createSequentialGroup()
                                            .addComponent(jLabel20)
                                            .addGap(18, 18, 18)
                                            .addComponent(rSComboMetro11, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel23))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel8Layout.createSequentialGroup()
                                    .addGap(12, 12, 12)
                                    .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabel22)
                                        .addComponent(jLabel19))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel21))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel8Layout.createSequentialGroup()
                                    .addGap(84, 84, 84)
                                    .addComponent(rSMTextFull17, javax.swing.GroupLayout.PREFERRED_SIZE, 401, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(0, 45, Short.MAX_VALUE)))
                            .addGap(18, 18, 18)
                            .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(rSComboMetro9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(rSMTextFull16, javax.swing.GroupLayout.DEFAULT_SIZE, 325, Short.MAX_VALUE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(rSComboMetro3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(0, 92, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(rSButton4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(rSButton3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(125, 125, 125))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(jLabel17)
                        .addGap(55, 55, 55)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel16)
                            .addComponent(rSMTextFull10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(39, 39, 39)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel18)
                            .addComponent(rSComboMetro10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(33, 33, 33)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel20)
                            .addComponent(rSComboMetro11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel23)
                            .addComponent(rSComboMetro9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(rSComboMetro3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel19)
                            .addComponent(rSMTextFull18, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel21)
                            .addComponent(rSMTextFull16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(38, 38, 38)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel22)
                    .addComponent(rSMTextFull17, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(116, 116, 116)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rSButton3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rSButton4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(66, 66, 66))
        );

        javax.swing.GroupLayout PUESTOLayout = new javax.swing.GroupLayout(PUESTO);
        PUESTO.setLayout(PUESTOLayout);
        PUESTOLayout.setHorizontalGroup(
            PUESTOLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PUESTOLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(350, Short.MAX_VALUE))
        );
        PUESTOLayout.setVerticalGroup(
            PUESTOLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PUESTOLayout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(41, 41, 41))
        );

        jTabbedPane1.addTab("NUEVA CONSULTA", PUESTO);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 769, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PUESTO;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextArea jTextArea1;
    private rojeru_san.RSButton rSButton2;
    private rojeru_san.RSButton rSButton3;
    private rojeru_san.RSButton rSButton4;
    private rojerusan.RSComboMetro rSComboMetro10;
    private rojerusan.RSComboMetro rSComboMetro11;
    private rojerusan.RSComboMetro rSComboMetro2;
    private rojerusan.RSComboMetro rSComboMetro3;
    private rojerusan.RSComboMetro rSComboMetro6;
    private rojerusan.RSComboMetro rSComboMetro7;
    private rojerusan.RSComboMetro rSComboMetro8;
    private rojerusan.RSComboMetro rSComboMetro9;
    private rojeru_san.RSMTextFull rSMTextFull1;
    private rojeru_san.RSMTextFull rSMTextFull10;
    private rojeru_san.RSMTextFull rSMTextFull11;
    private rojeru_san.RSMTextFull rSMTextFull12;
    private rojeru_san.RSMTextFull rSMTextFull13;
    private rojeru_san.RSMTextFull rSMTextFull14;
    private rojeru_san.RSMTextFull rSMTextFull15;
    private rojeru_san.RSMTextFull rSMTextFull16;
    private rojeru_san.RSMTextFull rSMTextFull17;
    private rojeru_san.RSMTextFull rSMTextFull18;
    private rojeru_san.RSMTextFull rSMTextFull8;
    private rojeru_san.complementos.RSTableMetro rSTableMetro1;
    // End of variables declaration//GEN-END:variables
}
