/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package paneles;

/**
 *
 * @author crist
 */
public class pnlPacientes extends javax.swing.JFrame {

    /**
     * Creates new form pnlPacientes
     */
    public pnlPacientes() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txtPuestos = new javax.swing.JLabel();
        lblPuesto = new javax.swing.JLabel();
        txtPuesto = new javax.swing.JTextField();
        btnGuardar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        btnModificar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        txtPuesto2 = new javax.swing.JTextField();
        txtPuesto5 = new javax.swing.JTextField();
        txtPuesto6 = new javax.swing.JTextField();
        lblPuesto1 = new javax.swing.JLabel();
        lblPuesto2 = new javax.swing.JLabel();
        lblPuesto3 = new javax.swing.JLabel();
        lblPuesto4 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jComboBox2 = new javax.swing.JComboBox<>();
        lblPuesto5 = new javax.swing.JLabel();
        txtPuesto7 = new javax.swing.JTextField();
        txtPuesto8 = new javax.swing.JTextField();
        lblPuesto6 = new javax.swing.JLabel();
        lblPuesto7 = new javax.swing.JLabel();
        lblPuesto8 = new javax.swing.JLabel();
        txtPuesto9 = new javax.swing.JTextField();
        lblPuesto9 = new javax.swing.JLabel();
        txtPuesto10 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(29, 27, 56));

        txtPuestos.setBackground(new java.awt.Color(231, 156, 194));
        txtPuestos.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        txtPuestos.setForeground(new java.awt.Color(231, 156, 194));
        txtPuestos.setText("Pacientes");

        lblPuesto.setBackground(new java.awt.Color(231, 156, 194));
        lblPuesto.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        lblPuesto.setForeground(new java.awt.Color(231, 156, 194));
        lblPuesto.setText("Nombre");

        txtPuesto.setBackground(new java.awt.Color(29, 27, 56));
        txtPuesto.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        txtPuesto.setForeground(new java.awt.Color(231, 156, 194));

        btnGuardar.setBackground(new java.awt.Color(231, 156, 194));
        btnGuardar.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnGuardar.setForeground(new java.awt.Color(0, 0, 0));
        btnGuardar.setText("GUARDAR");

        jTable1.setBackground(new java.awt.Color(255, 255, 255));
        jTable1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jTable1.setForeground(new java.awt.Color(0, 0, 0));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Codigo", "Nombre", "Apellido", "Direccion", "Telefono", "Telefono", "Estado civil", "Sexo", "Encargado", "DUI", "Fecha Nciemiento"
            }
        ));
        jTable1.setSelectionBackground(new java.awt.Color(246, 190, 214));
        jScrollPane1.setViewportView(jTable1);

        btnModificar.setBackground(new java.awt.Color(231, 156, 194));
        btnModificar.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnModificar.setForeground(new java.awt.Color(0, 0, 0));
        btnModificar.setText("MODIFICAR");

        btnEliminar.setBackground(new java.awt.Color(231, 156, 194));
        btnEliminar.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnEliminar.setForeground(new java.awt.Color(0, 0, 0));
        btnEliminar.setText("ELIMINAR");

        txtPuesto2.setBackground(new java.awt.Color(29, 27, 56));
        txtPuesto2.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        txtPuesto2.setForeground(new java.awt.Color(231, 156, 194));

        txtPuesto5.setBackground(new java.awt.Color(29, 27, 56));
        txtPuesto5.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        txtPuesto5.setForeground(new java.awt.Color(231, 156, 194));

        txtPuesto6.setBackground(new java.awt.Color(29, 27, 56));
        txtPuesto6.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        txtPuesto6.setForeground(new java.awt.Color(231, 156, 194));

        lblPuesto1.setBackground(new java.awt.Color(231, 156, 194));
        lblPuesto1.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        lblPuesto1.setForeground(new java.awt.Color(231, 156, 194));
        lblPuesto1.setText("Dirección");

        lblPuesto2.setBackground(new java.awt.Color(231, 156, 194));
        lblPuesto2.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        lblPuesto2.setForeground(new java.awt.Color(231, 156, 194));
        lblPuesto2.setText("Apellido");

        lblPuesto3.setBackground(new java.awt.Color(231, 156, 194));
        lblPuesto3.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        lblPuesto3.setForeground(new java.awt.Color(231, 156, 194));
        lblPuesto3.setText("Telefono");

        lblPuesto4.setBackground(new java.awt.Color(231, 156, 194));
        lblPuesto4.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        lblPuesto4.setForeground(new java.awt.Color(231, 156, 194));
        lblPuesto4.setText("Estado Civil");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione", "Masculino", "Femenino" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione", "Casada", "Soltera", "Viuda", " " }));
        jComboBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox2ActionPerformed(evt);
            }
        });

        lblPuesto5.setBackground(new java.awt.Color(231, 156, 194));
        lblPuesto5.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        lblPuesto5.setForeground(new java.awt.Color(231, 156, 194));
        lblPuesto5.setText("Sexo");

        txtPuesto7.setBackground(new java.awt.Color(29, 27, 56));
        txtPuesto7.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        txtPuesto7.setForeground(new java.awt.Color(231, 156, 194));

        txtPuesto8.setBackground(new java.awt.Color(29, 27, 56));
        txtPuesto8.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        txtPuesto8.setForeground(new java.awt.Color(231, 156, 194));

        lblPuesto6.setBackground(new java.awt.Color(231, 156, 194));
        lblPuesto6.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        lblPuesto6.setForeground(new java.awt.Color(231, 156, 194));
        lblPuesto6.setText("Encargado");

        lblPuesto7.setBackground(new java.awt.Color(231, 156, 194));
        lblPuesto7.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        lblPuesto7.setForeground(new java.awt.Color(231, 156, 194));
        lblPuesto7.setText("Nac.");

        lblPuesto8.setBackground(new java.awt.Color(231, 156, 194));
        lblPuesto8.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        lblPuesto8.setForeground(new java.awt.Color(231, 156, 194));
        lblPuesto8.setText("DUI");

        txtPuesto9.setBackground(new java.awt.Color(29, 27, 56));
        txtPuesto9.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        txtPuesto9.setForeground(new java.awt.Color(231, 156, 194));

        lblPuesto9.setBackground(new java.awt.Color(231, 156, 194));
        lblPuesto9.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        lblPuesto9.setForeground(new java.awt.Color(231, 156, 194));
        lblPuesto9.setText("Buscar");

        txtPuesto10.setBackground(new java.awt.Color(29, 27, 56));
        txtPuesto10.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        txtPuesto10.setForeground(new java.awt.Color(231, 156, 194));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(395, 395, 395)
                        .addComponent(txtPuestos))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnEliminar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnModificar)
                                .addGap(6, 6, 6))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(lblPuesto)
                                            .addComponent(lblPuesto1)
                                            .addComponent(lblPuesto2)
                                            .addComponent(lblPuesto3)
                                            .addComponent(lblPuesto4)
                                            .addComponent(lblPuesto5))
                                        .addGap(18, 18, 18))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lblPuesto7)
                                            .addComponent(lblPuesto8))
                                        .addGap(26, 26, 26)))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jComboBox1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jComboBox2, 0, 221, Short.MAX_VALUE)
                                    .addComponent(txtPuesto2)
                                    .addComponent(txtPuesto)
                                    .addComponent(txtPuesto5, javax.swing.GroupLayout.DEFAULT_SIZE, 221, Short.MAX_VALUE)
                                    .addComponent(txtPuesto6, javax.swing.GroupLayout.DEFAULT_SIZE, 221, Short.MAX_VALUE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addComponent(txtPuesto7))))
                            .addComponent(txtPuesto9, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lblPuesto6)
                                .addGap(18, 18, 18)
                                .addComponent(txtPuesto8, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lblPuesto9)
                                .addGap(18, 18, 18)
                                .addComponent(txtPuesto10, javax.swing.GroupLayout.PREFERRED_SIZE, 416, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 380, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(txtPuestos)
                .addGap(45, 45, 45)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblPuesto)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtPuesto, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblPuesto9)
                        .addComponent(txtPuesto10, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtPuesto2, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblPuesto2))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtPuesto6, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblPuesto1))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtPuesto5, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblPuesto3))
                        .addGap(37, 37, 37)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblPuesto4)
                            .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPuesto5))
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPuesto8, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPuesto6))
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPuesto7, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPuesto8))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtPuesto9, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPuesto7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGuardar)
                    .addComponent(btnModificar)
                    .addComponent(btnEliminar))
                .addGap(135, 135, 135))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(pnlPacientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(pnlPacientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(pnlPacientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(pnlPacientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new pnlPacientes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnModificar;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lblPuesto;
    private javax.swing.JLabel lblPuesto1;
    private javax.swing.JLabel lblPuesto2;
    private javax.swing.JLabel lblPuesto3;
    private javax.swing.JLabel lblPuesto4;
    private javax.swing.JLabel lblPuesto5;
    private javax.swing.JLabel lblPuesto6;
    private javax.swing.JLabel lblPuesto7;
    private javax.swing.JLabel lblPuesto8;
    private javax.swing.JLabel lblPuesto9;
    private javax.swing.JTextField txtPuesto;
    private javax.swing.JTextField txtPuesto10;
    private javax.swing.JTextField txtPuesto2;
    private javax.swing.JTextField txtPuesto5;
    private javax.swing.JTextField txtPuesto6;
    private javax.swing.JTextField txtPuesto7;
    private javax.swing.JTextField txtPuesto8;
    private javax.swing.JTextField txtPuesto9;
    private javax.swing.JLabel txtPuestos;
    // End of variables declaration//GEN-END:variables
}
